// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "bluprnt-webapp-20200118232655-hostingbucket-bluprnt",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "https://d2dv9rwnsosd5t.cloudfront.net"
};


export default awsmobile;
